version: 2

sources:
  - name: globepay
    schema: raw
    tables:
      - name: acceptance
        loaded_at_field: date_time
        freshness:
          warn_after: {count: 24, period: hour}
      - name: chargeback
